In [2]:
import scipy
from scipy.linalg import hadamard
import math
import numpy as np
import matplotlib
from math import factorial
from matplotlib import pyplot as plt
from sympy.functions.combinatorial.numbers import stirling
from scipy.stats import norm
from scipy.misc import comb
import random
import itertools
from collections import namedtuple
%matplotlib inline

In [18]:
def count_ones(number):
    result = 0
    while number:
        number &= (number - 1)
        result += 1
    return result

wt = weight = count_ones

In [3]:
H4 = hadamard(2**4)
print(H4)

[[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1]
 [ 1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1  1 -1 -1]
 [ 1 -1 -1  1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1]
 [ 1  1  1  1 -1 -1 -1 -1  1  1  1  1 -1 -1 -1 -1]
 [ 1 -1  1 -1 -1  1 -1  1  1 -1  1 -1 -1  1 -1  1]
 [ 1  1 -1 -1 -1 -1  1  1  1  1 -1 -1 -1 -1  1  1]
 [ 1 -1 -1  1 -1  1  1 -1  1 -1 -1  1 -1  1  1 -1]
 [ 1  1  1  1  1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 1 -1  1 -1  1 -1  1 -1 -1  1 -1  1 -1  1 -1  1]
 [ 1  1 -1 -1  1  1 -1 -1 -1 -1  1  1 -1 -1  1  1]
 [ 1 -1 -1  1  1 -1 -1  1 -1  1  1 -1 -1  1  1 -1]
 [ 1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1  1  1  1  1]
 [ 1 -1  1 -1 -1  1 -1  1 -1  1 -1  1  1 -1  1 -1]
 [ 1  1 -1 -1 -1 -1  1  1 -1 -1  1  1  1  1 -1 -1]
 [ 1 -1 -1  1 -1  1  1 -1 -1  1  1 -1  1 -1 -1  1]]


In [48]:
print(H4[2])

[ 1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1  1 -1 -1]


In [47]:
m = 3
ones_limit = 3
H = hadamard(2**(2*m))
low_mask = (1 << m) - 1
rows_to_check = [v for v in range(2**(2*m)) if v & low_mask and count_ones(v) <= ones_limit]

# Отладка.
print('Маска:', bin(low_mask))
print('Проверяемые строчки:', rows_to_check)

block_size = 2 ** m

for coeffs in itertools.product(range(2**m), repeat=2**m):
    for row in rows_to_check:
        summary = 0
        for i in range(len(coeffs)):
            summary += H[row, coeffs[i] + i*block_size]
        if summary != 0:
            break
    else:
        print('Решение:', coeffs)
print('Завершено.')


Маска: 0b111
Проверяемые строчки: [1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 17, 18, 19, 20, 21, 22, 25, 26, 28, 33, 34, 35, 36, 37, 38, 41, 42, 44, 49, 50, 52]
Завершено.


In [10]:
m = np.zeros((2**4, 2**4), dtype=int)
m = np.asmatrix(m)

for i in range(2**4):
    for j in range(2**4):
        m[i, j] = (-1)**count_ones(i & j)

print(m)
print(H4 == m)

[[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1]
 [ 1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1  1 -1 -1]
 [ 1 -1 -1  1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1]
 [ 1  1  1  1 -1 -1 -1 -1  1  1  1  1 -1 -1 -1 -1]
 [ 1 -1  1 -1 -1  1 -1  1  1 -1  1 -1 -1  1 -1  1]
 [ 1  1 -1 -1 -1 -1  1  1  1  1 -1 -1 -1 -1  1  1]
 [ 1 -1 -1  1 -1  1  1 -1  1 -1 -1  1 -1  1  1 -1]
 [ 1  1  1  1  1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 1 -1  1 -1  1 -1  1 -1 -1  1 -1  1 -1  1 -1  1]
 [ 1  1 -1 -1  1  1 -1 -1 -1 -1  1  1 -1 -1  1  1]
 [ 1 -1 -1  1  1 -1 -1  1 -1  1  1 -1 -1  1  1 -1]
 [ 1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1  1  1  1  1]
 [ 1 -1  1 -1 -1  1 -1  1 -1  1 -1  1  1 -1  1 -1]
 [ 1  1 -1 -1 -1 -1  1  1 -1 -1  1  1  1  1 -1 -1]
 [ 1 -1 -1  1 -1  1  1 -1 -1  1  1 -1  1 -1 -1  1]]
[[ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True
   True 

In [17]:
def sum_digits(n):
    return sum(map(int, str(n)))
               
print(sum_digits(999))
print(sum_digits(151))
print(sum_digits(999**3))

27
7
54


In [19]:
def Q(f):
    m = round(math.log(len(f), 2))
    min_weight = 2 * m
    
    for b in range(1, len(f)):
        for a in range(len(f)):
            current_weight = 0
            for x in range(len(f)):
                if wt(a & x) ^ wt(b & f[x]):
                    current_weight += 1
            if current_weight != (1 << (m - 1)):
                min_weight = min(min_weight, wt(a) + wt(b))
    return min_weight

In [26]:
def int_to_vector(value, size):
    return np.unpackbits(np.array([value], dtype=np.uint8))[-size:]

print(int_to_vector(7, 5))

[0 0 1 1 1]


In [ ]:
def all_mappings(n):
    for i in range(2**n):
        

In [36]:
m = 1
for i in range(2**(2 * m)):
    f = int_to_vector(i, m << 1)
    print(Q(f))

1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


In [51]:
def power_module(value, power, module):
    value = value % module
    if power == 0:
        return 1
    if power == 1:
        return value
    if power & 1:
        return (value * power_module(value ** 2, power >> 1, module)) % module
    else:
        return power_module(value ** 2, power >> 1, module)
    
print(power_module(7, 5, 1241453454))
print(power_module(7, 4, 1241453454))

16807
2401


In [58]:
g = 2**88 + 2**8 + 59
m = 2**128

print((power_module(g, 2**10, m) - 1) % m)

135530025446068214149251921578638766080


In [53]:
def fnv2(x):
    h0 = 144066263297769815596495629667062367629
    g = 2**88 + 315
    m = 2**128
    result = h0
    
    for byte in x:
        result = (result + byte) * g % m
    return result

In [54]:
fnv2(bytes([1]))

279349696642573673308240645220056307130

In [55]:
fnv2(bytes([1] + [0] * 126))

324817379259453764073636455151046050762

In [2]:
'0' * 32

'00000000000000000000000000000000'

In [1]:
def string_to_abcd(s):
    a = int(s[:8], 16)
    b = int(s[8: 16], 16)
    c = int(s[16: 24], 16)
    d = int(s[24: 32], 16)
    return (a, b, c, d)

In [3]:
def find_S2(plaintext, ciphertext):
    a, b, c, d = string_to_abcd(plaintext)
    a6, b6, c6, d6 = string_to_abcd(ciphertext)
    return b ^ c ^ d ^ a6 ^ b6 ^ c6

In [ ]:
def study_difference(plaintext, ciphertext):
    